# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=[VERSION]
yarn_mappings=[VERSION]
loader_version=0.16.10

# Mod Properties
mod_version=1.0.0-alpha.5
maven_group=com.awakenedredstone
archives_base_name=default-components

# Dependencies
fabric_version=[VERSION]
packet_tweaker=[VERSION]
#owo_version=0.12.10+1.21
#jankson_version=1.2.2
